# Global Population Growth Analysis and Future Population Prediction Using Machine Learning

## 2. Data Understanding

This notebook focuses on understanding the World Bank population dataset before data cleaning and exploratory data analysis.

The dataset contains population information for countries and other World Bank entities over multiple years.

In [1]:
import pandas as pd
from pathlib import Path

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
BASE_DIR = Path.cwd().parent

RAW_DATA_PATH = (
    BASE_DIR
    / "data"
    / "raw"
    / "API_SP.POP.TOTL_DS2_en_csv_v2_350115.csv"
)

df = pd.read_csv(RAW_DATA_PATH, skiprows=4)

print("Raw dataset loaded successfully!")

Raw dataset loaded successfully!

In [3]:
print("Number of rows    :", df.shape[0])
print("Number of columns :", df.shape[1])
print("Dataset shape     :", df.shape)

Number of rows    : 265
Number of columns : 71
Dataset shape     : (265, 71)

In [4]:
df.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,108785.0,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,788844284.0,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,43844111.0,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106384410.0,108754449.0,...,440150152.0,451395343.0,462522286.0,473687685.0,484978794.0,496366058.0,508318102.0,520655398.0,532809933.0,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,39040039.0,NaN
5,Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,...,2648285.0,2607733.0,2567801.0,2528480.0,2489762.0,2451636.0,2411658.0,2377128.0,2349580.0,NaN
6,Andorra,AND,"Population, total",SP.POP.TOTL,9510.0,10283.0,11086.0,11915.0,12764.0,13634.0,...,73763.0,75162.0,76474.0,77380.0,78364.0,79705.0,80856.0,81938.0,82904.0,NaN
7,Arab World,ARB,"Population, total",SP.POP.TOTL,91540853.0,93931683.0,96428599.0,99038509.0,101729760.0,104494008.0,...,428315886.0,435998060.0,444281315.0,453723239.0,460646603.0,471352066.0,482105978.0,492612632.0,503356133.0,NaN
8,United Arab Emirates,ARE,"Population, total",SP.POP.TOTL,131334.0,137989.0,144946.0,152211.0,159692.0,167103.0,...,9223225.0,9346701.0,9445785.0,9401038.0,9575152.0,10074977.0,10483751.0,10986400.0,11513149.0,NaN
9,Argentina,ARG,"Population, total",SP.POP.TOTL,20386045.0,20726276.0,21072538.0,21421705.0,21769453.0,22112629.0,...,44288894.0,44654882.0,44973465.0,45191965.0,45312281.0,45407904.0,45538401.0,45696159.0,45851378.0,NaN

In [5]:
df.tail(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
255,Virgin Islands (U.S.),VIR,"Population, total",SP.POP.TOTL,3.250000e+04,3.430000e+04,3.500000e+04,3.980000e+04,4.080000e+04,4.350000e+04,...,1.072810e+05,1.070010e+05,1.066690e+05,1.062900e+05,1.058700e+05,1.054130e+05,1.049170e+05,1.043770e+05,1.037920e+05,NaN
256,Viet Nam,VNM,"Population, total",SP.POP.TOTL,3.253193e+07,3.340906e+07,3.428856e+07,3.524910e+07,3.620156e+07,3.712966e+07,...,9.517698e+07,9.623732e+07,9.717378e+07,9.807919e+07,9.893510e+07,9.968066e+07,1.003522e+08,1.009877e+08,1.015985e+08,NaN
257,Vanuatu,VUT,"Population, total",SP.POP.TOTL,6.443100e+04,6.626400e+04,6.817400e+04,7.015900e+04,7.221900e+04,7.435800e+04,...,2.785070e+05,2.852590e+05,2.919850e+05,2.988580e+05,3.058680e+05,3.130460e+05,3.204090e+05,3.277770e+05,3.351690e+05,NaN
258,World,WLD,"Population, total",SP.POP.TOTL,3.021513e+09,3.062768e+09,3.117372e+09,3.184063e+09,3.251249e+09,3.318979e+09,...,7.613789e+09,7.696160e+09,7.777162e+09,7.853863e+09,7.919568e+09,7.988550e+09,8.062923e+09,8.140898e+09,8.215425e+09,NaN
259,Samoa,WSM,"Population, total",SP.POP.TOTL,1.124900e+05,1.154960e+05,1.185970e+05,1.217640e+05,1.248940e+05,1.279780e+05,...,2.054150e+05,2.075820e+05,2.097800e+05,2.119440e+05,2.137790e+05,2.152610e+05,2.166630e+05,2.180190e+05,2.193060e+05,NaN
260,Kosovo,XKX,"Population, total",SP.POP.TOTL,9.848460e+05,1.011421e+06,1.036950e+06,1.062737e+06,1.090270e+06,1.120168e+06,...,1.791019e+06,1.797086e+06,1.788891e+06,1.790151e+06,1.786079e+06,1.768096e+06,1.682668e+06,1.594353e+06,1.576876e+06,NaN
261,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5.532301e+06,5.655232e+06,5.782221e+06,5.911135e+06,6.048006e+06,6.195593e+06,...,3.309092e+07,3.408518e+07,3.511141e+07,3.613486e+07,3.714023e+07,3.822288e+07,3.939080e+07,4.058316e+07,4.177388e+07,NaN
262,South Africa,ZAF,"Population, total",SP.POP.TOTL,1.644017e+07,1.690804e+07,1.741852e+07,1.795456e+07,1.851136e+07,1.908938e+07,...,5.763516e+07,5.861300e+07,5.958788e+07,6.056238e+07,6.150260e+07,6.237841e+07,6.321238e+07,6.400719e+07,6.474732e+07,NaN
263,Zambia,ZMB,"Population, total",SP.POP.TOTL,3.153729e+06,3.254086e+06,3.358099e+06,3.465907e+06,3.577017e+06,3.692086e+06,...,1.744132e+07,1.797357e+07,1.851384e+07,1.905940e+07,1.960361e+07,2.015294e+07,2.072396e+07,2.131496e+07,2.191387e+07,NaN
264,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3.809389e+06,3.930401e+06,4.055959e+06,4.185877e+06,4.320006e+06,4.458462e+06,...,1.481248e+07,1.503445e+07,1.527137e+07,1.552689e+07,1.579721e+07,1.606906e+07,1.634082e+07,1.663437e+07,1.695080e+07,NaN

In [6]:
print("Dataset Columns:\n")

for column in df.columns:
    print(column)

Dataset Columns:

Country Name
Country Code
Indicator Name
Indicator Code
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
Unnamed: 70

In [7]:
print("Data Types:\n")
print(df.dtypes)

Data Types:

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960              float64
                   ...
2022              float64
2023              float64
2024              float64
2025              float64
Unnamed: 70       float64
Length: 71, dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    265 non-null    object
 1   Country Code    265 non-null    object
 2   Indicator Name  265 non-null    object
 3   Indicator Code  265 non-null    object
 4   1960            263 non-null    float64
 5   1961            263 non-null    float64
 6   1962            263 non-null    float64
 7   1963            263 non-null    float64
 8   1964            263 non-null    float64
 9   1965            263 non-null    float64
 10  1966            263 non-null    float64
 11  1967            263 non-null    float64
 12  1968            263 non-null    float64
 13  1969            263 non-null    float64
 14  1970            263 non-null    float64
 15  1971            263 non-null    float64
 16  1972            263 non-null    float64
 17  1973            263 non-null    float64
 18  1974            263 non-null    float64
 19  1975            263 non-null    float64
 20  1976            263 non-null    float64
 21  1977            263 non-null    float64
 22  1978            263 non-null    float64
 23  1979            263 non-null    float64
 24  1980            263 non-null    float64
 25  1981            263 non-null    float64
 26  1982            263 non-null    float64
 27  1983            263 non-null    float64
 28  1984            263 non-null    float64
 29  1985            263 non-null    float64
 30  1986            263 non-null    float64
 31  1987            263 non-null    float64
 32  1988            263 non-null    float64
 33  1989            263 non-null    float64
 34  1990            264 non-null    float64
 35  1991            264 non-null    float64
 36  1992            264 non-null    float64
 37  1993            264 non-null    float64
 38  1994            264 non-null    float64
 39  1995            264 non-null    float64
 40  1996            264 non-null    float64
 41  1997            264 non-null    float64
 42  1998            264 non-null    float64
 43  1999            264 non-null    float64
 44  2000            264 non-null    float64
 45  2001            264 non-null    float64
 46  2002            264 non-null    float64
 47  2003            264 non-null    float64
 48  2004            264 non-null    float64
 49  2005            264 non-null    float64
 50  2006            264 non-null    float64
 51  2007            264 non-null    float64
 52  2008            264 non-null    float64
 53  2009            264 non-null    float64
 54  2010            264 non-null    float64
 55  2011            264 non-null    float64
 56  2012            264 non-null    float64
 57  2013            264 non-null    float64
 58  2014            264 non-null    float64
 59  2015            264 non-null    float64
 60  2016            264 non-null    float64
 61  2017            264 non-null    float64
 62  2018            264 non-null    float64
 63  2019            264 non-null    float64
 64  2020            264 non-null    float64
 65  2021            264 non-null    float64
 66  2022            264 non-null    float64
 67  2023            264 non-null    float64
 68  2024            264 non-null    float64
 69  2025            264 non-null    float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), object(4)
memory usage: 147.1+ KB

In [9]:
df.describe()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
count,2.630000e+02,2.630000e+02,2.630000e+02,2.630000e+02,2.630000e+02,2.630000e+02,2.630000e+02,2.630000e+02,2.630000e+02,2.630000e+02,...,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,0.0
mean,1.153120e+08,1.169136e+08,1.190730e+08,1.217435e+08,1.244376e+08,1.271629e+08,1.300074e+08,1.328586e+08,1.357846e+08,1.388116e+08,...,3.072039e+08,3.108970e+08,3.145325e+08,3.180055e+08,3.211230e+08,3.242488e+08,3.275260e+08,3.309670e+08,3.343474e+08,NaN
std,3.634718e+08,3.679838e+08,3.746600e+08,3.833160e+08,3.920191e+08,4.008289e+08,4.101173e+08,4.193912e+08,4.289305e+08,4.388358e+08,...,9.616553e+08,9.723409e+08,9.827317e+08,9.925628e+08,1.001301e+09,1.009774e+09,1.018613e+09,1.027953e+09,1.037190e+09,NaN
min,2.715000e+03,2.970000e+03,3.264000e+03,3.584000e+03,3.922000e+03,4.282000e+03,4.664000e+03,5.071000e+03,5.500000e+03,5.631000e+03,...,1.086900e+04,1.075100e+04,1.058100e+04,1.039900e+04,1.019400e+04,9.992000e+03,9.816000e+03,9.646000e+03,9.492000e+03,NaN
25%,5.142405e+05,5.231040e+05,5.324175e+05,5.422090e+05,5.524615e+05,5.604860e+05,5.697490e+05,5.749720e+05,5.810680e+05,5.851710e+05,...,1.733863e+06,1.751920e+06,1.759212e+06,1.771730e+06,1.779256e+06,1.794683e+06,1.791529e+06,1.766858e+06,1.765773e+06,NaN
50%,3.645600e+06,3.715534e+06,3.806307e+06,3.900506e+06,3.997305e+06,4.096157e+06,4.197926e+06,4.292572e+06,4.388944e+06,4.488232e+06,...,1.024669e+07,1.022952e+07,1.035482e+07,1.052565e+07,1.046079e+07,1.047541e+07,1.061151e+07,1.086537e+07,1.091204e+07,NaN
75%,2.593206e+07,2.668329e+07,2.742502e+07,2.817681e+07,2.892154e+07,2.966692e+07,3.042106e+07,3.105907e+07,3.156648e+07,3.204628e+07,...,5.822693e+07,5.892906e+07,5.962318e+07,6.066499e+07,6.183456e+07,6.296176e+07,6.406369e+07,6.514330e+07,6.574057e+07,NaN
max,3.021513e+09,3.062768e+09,3.117372e+09,3.184063e+09,3.251249e+09,3.318979e+09,3.389042e+09,3.458932e+09,3.530577e+09,3.604694e+09,...,7.613789e+09,7.696160e+09,7.777162e+09,7.853863e+09,7.919568e+09,7.988550e+09,8.062923e+09,8.140898e+09,8.215425e+09,NaN

In [10]:
print("Total World Bank entities:", df["Country Name"].nunique())

Total World Bank entities: 265

In [11]:
print("First 30 entities:\n")

print(df["Country Name"].unique()[:30])

First 30 entities:

['Aruba' 'Africa Eastern and Southern' 'Afghanistan'
 'Africa Western and Central' 'Angola' 'Albania' 'Andorra' 'Arab World'
 'United Arab Emirates' 'Argentina' 'Armenia' 'American Samoa'
 'Antigua and Barbuda' 'Australia' 'Austria' 'Azerbaijan' 'Burundi'
 'Belgium' 'Benin' 'Burkina Faso' 'Bangladesh' 'Bulgaria' 'Bahrain'
 'Bahamas, The' 'Bosnia and Herzegovina' 'Belarus' 'Belize' 'Bermuda'
 'Bolivia' 'Brazil']

In [12]:
year_columns = [
    column for column in df.columns
    if str(column).isdigit()
]

print("First year:", year_columns[0])
print("Last year :", year_columns[-1])
print("Number of years:", len(year_columns))

First year: 1960
Last year : 2025
Number of years: 66

In [13]:
missing_values = df.isnull().sum()

print("Missing values by column:\n")
print(missing_values[missing_values > 0])

Missing values by column:

1960             2
1961             2
1962             2
1963             2
1964             2
              ...
2022             1
2023             1
2024             1
2025             1
Unnamed: 70    265
Length: 67, dtype: int64

In [14]:
duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

Duplicate rows: 0

In [15]:
print("Indicator Names:\n")
print(df["Indicator Name"].unique())

Indicator Names:

['Population, total']

In [16]:
print("Number of unique country/entity codes:",
      df["Country Code"].nunique())

Number of unique country/entity codes: 265

In [17]:
print("=" * 60)
print("DATA UNDERSTANDING SUMMARY")
print("=" * 60)

print(f"Total rows/entities       : {df.shape[0]}")
print(f"Total columns             : {df.shape[1]}")
print(f"Number of unique entities : {df['Country Name'].nunique()}")
print(f"First year                : {year_columns[0]}")
print(f"Last year                 : {year_columns[-1]}")
print(f"Number of years           : {len(year_columns)}")
print(f"Indicator                 : {df['Indicator Name'].iloc[0]}")
print(f"Indicator Code            : {df['Indicator Code'].iloc[0]}")
print(f"Duplicate rows            : {df.duplicated().sum()}")
print(f"Total missing values      : {df.isnull().sum().sum()}")

print("=" * 60)

============================================================
DATA UNDERSTANDING SUMMARY
============================================================
Total rows/entities       : 265
Total columns             : 71
Number of unique entities : 265
First year                : 1960
Last year                 : 2025
Number of years           : 66
Indicator                 : Population, total
Indicator Code            : SP.POP.TOTL
Duplicate rows            : 0
Total missing values      : 361
============================================================