# STEP 5 — Feature Engineering

## Objective

The objective of this step is to create additional features from the cleaned population dataset for machine learning.

### Features to be Created

- Previous Year Population
- Population Growth Percentage
- Population Lag 2
- 3-Year Rolling Average Population

These features will help machine learning models learn population trends and historical patterns.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    "../data/processed/Global_Population_Cleaned.csv"
)

df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population
0,Afghanistan,AFG,"Population, total",SP.POP.TOTL,1960,9035043.0
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,1961,9214083.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,1962,9404406.0
3,Afghanistan,AFG,"Population, total",SP.POP.TOTL,1963,9604487.0
4,Afghanistan,AFG,"Population, total",SP.POP.TOTL,1964,9814318.0

In [3]:
df = df.sort_values(
    ["Country Code", "Year"]
).reset_index(drop=True)

df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population
0,Aruba,ABW,"Population, total",SP.POP.TOTL,1960,54922.0
1,Aruba,ABW,"Population, total",SP.POP.TOTL,1961,55578.0
2,Aruba,ABW,"Population, total",SP.POP.TOTL,1962,56320.0
3,Aruba,ABW,"Population, total",SP.POP.TOTL,1963,57002.0
4,Aruba,ABW,"Population, total",SP.POP.TOTL,1964,57619.0

In [4]:
df["Previous_Year_Population"] = (
    df.groupby("Country Code")["Population"]
      .shift(1)
)

df.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population,Previous_Year_Population
0,Aruba,ABW,"Population, total",SP.POP.TOTL,1960,54922.0,NaN
1,Aruba,ABW,"Population, total",SP.POP.TOTL,1961,55578.0,54922.0
2,Aruba,ABW,"Population, total",SP.POP.TOTL,1962,56320.0,55578.0
3,Aruba,ABW,"Population, total",SP.POP.TOTL,1963,57002.0,56320.0
4,Aruba,ABW,"Population, total",SP.POP.TOTL,1964,57619.0,57002.0
5,Aruba,ABW,"Population, total",SP.POP.TOTL,1965,58190.0,57619.0
6,Aruba,ABW,"Population, total",SP.POP.TOTL,1966,58694.0,58190.0
7,Aruba,ABW,"Population, total",SP.POP.TOTL,1967,58990.0,58694.0
8,Aruba,ABW,"Population, total",SP.POP.TOTL,1968,59069.0,58990.0
9,Aruba,ABW,"Population, total",SP.POP.TOTL,1969,59052.0,59069.0

Population Growth %

In [5]:
df["Population_Growth_Percentage"] = (
    df.groupby("Country Code")["Population"]
      .pct_change() * 100
)

df.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population,Previous_Year_Population,Population_Growth_Percentage
0,Aruba,ABW,"Population, total",SP.POP.TOTL,1960,54922.0,NaN,NaN
1,Aruba,ABW,"Population, total",SP.POP.TOTL,1961,55578.0,54922.0,1.194421
2,Aruba,ABW,"Population, total",SP.POP.TOTL,1962,56320.0,55578.0,1.335061
3,Aruba,ABW,"Population, total",SP.POP.TOTL,1963,57002.0,56320.0,1.210938
4,Aruba,ABW,"Population, total",SP.POP.TOTL,1964,57619.0,57002.0,1.082418
5,Aruba,ABW,"Population, total",SP.POP.TOTL,1965,58190.0,57619.0,0.990993
6,Aruba,ABW,"Population, total",SP.POP.TOTL,1966,58694.0,58190.0,0.866128
7,Aruba,ABW,"Population, total",SP.POP.TOTL,1967,58990.0,58694.0,0.504310
8,Aruba,ABW,"Population, total",SP.POP.TOTL,1968,59069.0,58990.0,0.133921
9,Aruba,ABW,"Population, total",SP.POP.TOTL,1969,59052.0,59069.0,-0.028780

Population Lag 2

In [6]:
df["Population_Lag_2"] = (
    df.groupby("Country Code")["Population"]
      .shift(2)
)

df.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population,Previous_Year_Population,Population_Growth_Percentage,Population_Lag_2
0,Aruba,ABW,"Population, total",SP.POP.TOTL,1960,54922.0,NaN,NaN,NaN
1,Aruba,ABW,"Population, total",SP.POP.TOTL,1961,55578.0,54922.0,1.194421,NaN
2,Aruba,ABW,"Population, total",SP.POP.TOTL,1962,56320.0,55578.0,1.335061,54922.0
3,Aruba,ABW,"Population, total",SP.POP.TOTL,1963,57002.0,56320.0,1.210938,55578.0
4,Aruba,ABW,"Population, total",SP.POP.TOTL,1964,57619.0,57002.0,1.082418,56320.0
5,Aruba,ABW,"Population, total",SP.POP.TOTL,1965,58190.0,57619.0,0.990993,57002.0
6,Aruba,ABW,"Population, total",SP.POP.TOTL,1966,58694.0,58190.0,0.866128,57619.0
7,Aruba,ABW,"Population, total",SP.POP.TOTL,1967,58990.0,58694.0,0.504310,58190.0
8,Aruba,ABW,"Population, total",SP.POP.TOTL,1968,59069.0,58990.0,0.133921,58694.0
9,Aruba,ABW,"Population, total",SP.POP.TOTL,1969,59052.0,59069.0,-0.028780,58990.0

3-Year Rolling Average

In [7]:
df["Population_Rolling_Avg_3"] = (
    df.groupby("Country Code")["Population"]
      .transform(
          lambda x: x.rolling(window=3, min_periods=1).mean()
      )
)

df.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population,Previous_Year_Population,Population_Growth_Percentage,Population_Lag_2,Population_Rolling_Avg_3
0,Aruba,ABW,"Population, total",SP.POP.TOTL,1960,54922.0,NaN,NaN,NaN,54922.000000
1,Aruba,ABW,"Population, total",SP.POP.TOTL,1961,55578.0,54922.0,1.194421,NaN,55250.000000
2,Aruba,ABW,"Population, total",SP.POP.TOTL,1962,56320.0,55578.0,1.335061,54922.0,55606.666667
3,Aruba,ABW,"Population, total",SP.POP.TOTL,1963,57002.0,56320.0,1.210938,55578.0,56300.000000
4,Aruba,ABW,"Population, total",SP.POP.TOTL,1964,57619.0,57002.0,1.082418,56320.0,56980.333333
5,Aruba,ABW,"Population, total",SP.POP.TOTL,1965,58190.0,57619.0,0.990993,57002.0,57603.666667
6,Aruba,ABW,"Population, total",SP.POP.TOTL,1966,58694.0,58190.0,0.866128,57619.0,58167.666667
7,Aruba,ABW,"Population, total",SP.POP.TOTL,1967,58990.0,58694.0,0.504310,58190.0,58624.666667
8,Aruba,ABW,"Population, total",SP.POP.TOTL,1968,59069.0,58990.0,0.133921,58694.0,58917.666667
9,Aruba,ABW,"Population, total",SP.POP.TOTL,1969,59052.0,59069.0,-0.028780,58990.0,59037.000000

In [8]:
df.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population,Previous_Year_Population,Population_Growth_Percentage,Population_Lag_2,Population_Rolling_Avg_3
0,Aruba,ABW,"Population, total",SP.POP.TOTL,1960,54922.0,NaN,NaN,NaN,54922.000000
1,Aruba,ABW,"Population, total",SP.POP.TOTL,1961,55578.0,54922.0,1.194421,NaN,55250.000000
2,Aruba,ABW,"Population, total",SP.POP.TOTL,1962,56320.0,55578.0,1.335061,54922.0,55606.666667
3,Aruba,ABW,"Population, total",SP.POP.TOTL,1963,57002.0,56320.0,1.210938,55578.0,56300.000000
4,Aruba,ABW,"Population, total",SP.POP.TOTL,1964,57619.0,57002.0,1.082418,56320.0,56980.333333
5,Aruba,ABW,"Population, total",SP.POP.TOTL,1965,58190.0,57619.0,0.990993,57002.0,57603.666667
6,Aruba,ABW,"Population, total",SP.POP.TOTL,1966,58694.0,58190.0,0.866128,57619.0,58167.666667
7,Aruba,ABW,"Population, total",SP.POP.TOTL,1967,58990.0,58694.0,0.504310,58190.0,58624.666667
8,Aruba,ABW,"Population, total",SP.POP.TOTL,1968,59069.0,58990.0,0.133921,58694.0,58917.666667
9,Aruba,ABW,"Population, total",SP.POP.TOTL,1969,59052.0,59069.0,-0.028780,58990.0,59037.000000

In [9]:
df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       'Year', 'Population', 'Previous_Year_Population',
       'Population_Growth_Percentage', 'Population_Lag_2',
       'Population_Rolling_Avg_3'],
      dtype='object')

In [10]:
df.isnull().sum()

Country Name                      0
Country Code                      0
Indicator Name                    0
Indicator Code                    0
Year                              0
Population                        0
Previous_Year_Population        217
Population_Growth_Percentage    217
Population_Lag_2                434
Population_Rolling_Avg_3          0
dtype: int64

In [11]:
ml_df = df.dropna(
    subset=[
        "Previous_Year_Population",
        "Population_Lag_2"
    ]
).copy()

ml_df.shape

(13858, 10)

In [12]:
output_path = "../data/processed/Global_Population_Feature_Engineered.csv"

ml_df.to_csv(
    output_path,
    index=False
)

print("Feature engineered dataset saved successfully.")
print(output_path)

Feature engineered dataset saved successfully.
../data/processed/Global_Population_Feature_Engineered.csv

In [13]:
check_df = pd.read_csv(output_path)

print("Shape:", check_df.shape)
print("Columns:")
print(check_df.columns.tolist())

Shape: (13858, 10)
Columns:
['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', 'Year', 'Population', 'Previous_Year_Population', 'Population_Growth_Percentage', 'Population_Lag_2', 'Population_Rolling_Avg_3']